// src/routes/_auth/verify-email.tsx
import { Suspense } from "react";

import { useEffect, useState } from "react";
import { createFileRoute, useNavigate, useSearch } from "@tanstack/react-router";
import { toast } from "sonner";
import { FieldDescription, FieldGroup } from "~/components/ui/field";
import { Button } from "~/components/ui/button";
import { Mail, CheckCircle2, AlertCircle } from "lucide-react";
import { authClient } from "~/lib/auth-client";
import { Link } from "@tanstack/react-router";
import { Spinner } from "~/components/ui/spinner";
import { seo } from '~/utils/seo'

export function VerifyEmailContent() {
  const [verifying, setVerifying] = useState(false);
  const [status, setStatus] = useState<"idle" | "success" | "error">("idle");
  const [errorMessage, setErrorMessage] = useState("");
  const navigate = useNavigate();
  const search = useSearch({ strict: false }) as any;
  const token = search.token;

  useEffect(() => {
    async function verify() {
      if (!token) return;

      setVerifying(true);
      try {
        const result = await authClient.verifyEmail({
          query: { token: token },
        });

        if (result.error) {
          setStatus("error");
          setErrorMessage(result.error.message || "Email verification failed.");
          toast.error(result.error.message || "Failed to verify email.");
        } else {
          setStatus("success");
          toast.success("Email verified successfully!");
          // Optional: auto-redirect after a delay
          setTimeout(() => navigate({ to: "/threads" }), 3000);
        }
      } catch (err) {
        console.error("Verify email error:", err);
        setStatus("error");
        setErrorMessage("An unexpected error occurred.");
        toast.error("An unexpected error occurred.");
      } finally {
        setVerifying(false);
      }
    }

    verify();
  }, [token, navigate]);
  return (
    <div className="flex flex-col gap-6">
      <FieldGroup>
        <div className="flex flex-col gap-2">
          {verifying && (
            <Spinner className="animate-spin size-8 text-primary" />
          )}
          {status === "success" && (
            <CheckCircle2 className="size-8 text-green-600" />
          )}
          {status === "error" && (
            <AlertCircle className="size-8 text-destructive" />
          )}
          {status === "idle" && <Mail className="size-8 text-primary" />}

          <h1 className="text-2xl font-bold">
            {verifying && "Verifying your email..."}
            {status === "success" && "Email verified!"}
            {status === "error" && "Verification failed"}
            {status === "idle" && "Verify your email"}
          </h1>

          <p className="text-muted-foreground text-sm">
            {verifying && "Please wait while we verify your email address..."}
            {status === "success" &&
              "Your email has been successfully verified. Redirecting to threads..."}
            {status === "error" && errorMessage}
            {status === "idle" &&
              "Click the link in your email to verify your account"}
          </p>
        </div>

        {status === "error" && (
          <div className="flex flex-col gap-3">
            <Button asChild className="w-full">
              <Link to="/sign-in">Back to sign in</Link>
            </Button>
            <Button variant="outline" asChild className="w-full">
              <Link to="/forgot-password">Request new verification</Link>
            </Button>
          </div>
        )}

        {status === "success" && (
          <FieldDescription>
            <Link
              to="/threads"
              className="text-sm underline underline-offset-4 hover:text-primary"
            >
              Go to threads
            </Link>
          </FieldDescription>
        )}
      </FieldGroup>
    </div>
  );
}
export const Route = createFileRoute('/_auth/verify-email')({
  head: () => ({
    meta: [...seo({ title: 'Verify Email - Foreum', description: 'Verify your email address.' })],
  }),
  component: VerifyEmail,
})

function VerifyEmail() {
  return (
 
    <Suspense fallback={<div>Loading...</div>}>
      <VerifyEmailContent />
    </Suspense>
 
  );
}

// src/routes/(auth)/verify-email/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import { authClient } from '$lib/auth-client';
	import { goto } from '$app/navigation';
	import * as Card from '$components/ui/card';
	import * as Alert from '$components/ui/alert';
	import { Loader2 } from '@lucide/svelte';
	import { Button } from '$components/ui/button';

	let verifying = $state(true);
	let error = $state<string | null>(null);
	let success = $state<string | null>(null);
	let loading = $state(true);
	const email = $derived(page.url.searchParams.get('email') || '');
	onMount(async () => {
		const token = page.url.searchParams.get('token');

		if (!token) {
			error = 'Invalid verification link.';
			verifying = false;
			return;
		}

		try {
			await authClient.verifyEmail({
				query: { token }
			});
			success = 'Your email has been verified successfully!';
			setTimeout(() => goto('/threads'), 2000);
		} catch (err: any) {
			error = err?.message || 'Failed to verify email. Please try again.';
		} finally {
			verifying = false;
		}
	});

	async function handleResend() {
		loading = true;
		try {
			await authClient.sendVerificationEmail({ email: email });
			success = 'Verification email resent! Please check your inbox.';
			error = null;
		} catch (err: any) {
			error = err?.message || 'Failed to resend verification email.';
		} finally {
			loading = false;
		}
	}
</script>

<Card.Root class="mx-auto mt-20 w-full max-w-md">
	<Card.Header class="space-y-2 text-center">
		<Card.Title class="text-xl font-semibold">Email Verification</Card.Title>
		<Card.Description>Please wait while we verify your email address.</Card.Description>
	</Card.Header>

	<Card.Content class="space-y-4 text-center">
		{#if verifying}
			<div class="flex items-center justify-center gap-2 text-muted-foreground">
				<Loader2 class="animate-spin" size={20} />
				<span>Verifying your email...</span>
			</div>
		{/if}
		{#if error}
			<Alert.Root variant="destructive">
				<Alert.Title>Verification Failed</Alert.Title>
				<Alert.Description>{error}</Alert.Description>
			</Alert.Root>

			<div class="mt-4 flex justify-center">
				<Button on:click={handleResend} disabled={loading}>
					{#if loading}
						Sending...
					{:else}
						Resend Verification Email
					{/if}
				</Button>
			</div>
		{/if}

		{#if success}
			<Alert.Root>
				<Alert.Title>Success</Alert.Title>
				<Alert.Description>{success}</Alert.Description>
			</Alert.Root>
		{/if}
	</Card.Content>
</Card.Root>
