// src/routes/(client-area)/profile/[username]/edit/+page.svelte
<script lang="ts">
	import { CheckCircle, Loader2, XCircle } from '@lucide/svelte';
	import { toast } from 'svelte-sonner';
	import { superForm } from 'sveltekit-superforms';
	import { zodClient } from 'sveltekit-superforms/adapters';

	import AvatarUpload from '$components/thread/AvatarUpload.svelte';
	import { Button } from '$components/ui/button';
	import * as Form from '$components/ui/form';
	import { Input } from '$components/ui/input';
	import { Textarea } from '$components/ui/textarea';
	import { isUsernameAvailable } from '$lib/auth-client';
	import { profileSchema } from '$lib/schemas';
	import { createTRPC } from '$lib/trpc';
	import { normalizeUsername } from '$utils';

	// ✅ use $props instead of export let
	let { data } = $props<{ data: import('./$types').PageData }>();

	const form = superForm(data.form, {
		validators: zodClient(profileSchema),
		onResult: ({ result }) => {
			if (result.status === 200) {
				toast.success('Profile updated successfully!');
			} else if (result.status >= 400) {
				toast.error(result.message ?? 'Failed to update profile.');
			}
		}
	});

	const { form: formData, enhance } = form;
	const trpc = createTRPC();

	let usernameStatus: 'available' | 'unavailable' | 'checking' | null = $state<any>(null);
	let usernameTimeout: ReturnType<typeof setTimeout>;
	let loading = $state(false);

	// ✅ reactive check for username availability
	$effect(() => {
		if ($formData.username) {
			clearTimeout(usernameTimeout);
			usernameTimeout = setTimeout(async () => {
				usernameStatus = 'checking';
				try {
					const res = await isUsernameAvailable({ username: $formData.username });
					usernameStatus = res.data?.available ? 'available' : 'unavailable';
				} catch {
					usernameStatus = null;
				}
			}, 500);
		}
	});

	async function handleSubmit() {
		if (usernameStatus === 'unavailable') {
			toast.error('Username is already taken.');
			return;
		}

		loading = true;
		try {
			await trpc.user.updateProfile.mutate({
				...$formData,
				username: normalizeUsername($formData.username)
			});
			toast.success('Profile updated successfully!');
		} catch {
			toast.error('Failed to update profile. Please try again.');
		} finally {
			loading = false;
		}
	}
</script>

<div class="container mx-auto max-w-2xl py-8">
	<h1 class="mb-6 text-3xl font-bold">Edit Profile</h1>

	<form use:enhance onsubmit={handleSubmit} class="space-y-6">
		<!-- Avatar -->
		<Form.Field {form} name="image">
			<Form.Control>
				{#snippet children()}
					<Form.Label>Profile Picture</Form.Label>
					<AvatarUpload value={$formData.image} on:change={(e) => ($formData.image = e.detail)} />
				{/snippet}
			</Form.Control>
		</Form.Field>

		<!-- Name -->
		<Form.Field {form} name="name">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Name</Form.Label>
					<Input placeholder="e.g. John Doe" {...props} bind:value={$formData.name} />
				{/snippet}
			</Form.Control>
		</Form.Field>

		<!-- Username with availability -->
		<Form.Field {form} name="username">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Username</Form.Label>
					<div class="relative flex items-center">
						<Input placeholder="Choose a username" class="pr-10" bind:value={$formData.username} />
						{#if usernameStatus === 'checking'}
							<Loader2 size={18} class="absolute right-3 animate-spin text-muted-foreground" />
						{:else if usernameStatus === 'available'}
							<CheckCircle size={18} class="absolute right-3 text-green-500" />
						{:else if usernameStatus === 'unavailable'}
							<XCircle size={18} class="absolute right-3 text-red-500" />
						{/if}
					</div>
				{/snippet}
			</Form.Control>
		</Form.Field>

		<!-- Bio -->
		<Form.Field {form} name="bio">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Bio</Form.Label>
					<Textarea placeholder="Tell us about yourself" {...props} bind:value={$formData.bio} />
				{/snippet}
			</Form.Control>
		</Form.Field>

		<!-- Location -->
		<Form.Field {form} name="location">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Location</Form.Label>
					<Input placeholder="e.g. Lagos, Nigeria" {...props} bind:value={$formData.location} />
				{/snippet}
			</Form.Control>
		</Form.Field>

		<!-- Website -->
		<Form.Field {form} name="website">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Website</Form.Label>
					<Input placeholder="https://yourwebsite.com" {...props} bind:value={$formData.website} />
				{/snippet}
			</Form.Control>
		</Form.Field>

		<div class="flex justify-end gap-4">
			<Button type="submit" disabled={loading || usernameStatus === 'unavailable'}>
				{#if loading}
					<Loader2 size={16} class="animate-spin" />
				{:else}
					Save Changes
				{/if}
			</Button>
		</div>
	</form>
</div>

// src/routes/_client/profile/$username/edit.tsx
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState, useEffect } from "react";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import { RichTextEditor } from "~/components/ui/rich-text-editor";
import { Label } from "~/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";
import { Avatar, AvatarFallback, AvatarImage } from "~/components/ui/avatar";
import { ArrowLeft, User } from "lucide-react";
import { trpc } from "~/lib/trpc";
import { toast } from "sonner";
import { useSession } from "~/lib/auth-client";
import { redirect } from "@tanstack/react-router";

export const Route = createFileRoute("/_client/profile/$username/edit")({
  component: EditProfilePage,
});

function EditProfilePage() {
  const { username } = Route.useParams();
  const navigate = useNavigate();
  const { data: session } = useSession();
  const utils = trpc.useUtils();

  const { data: profileUser, isLoading } = trpc.user.byUsername.useQuery({
    username,
  });

  const [name, setName] = useState("");
  const [usernameVal, setUsernameVal] = useState("");
  const [image, setImage] = useState("");
  const [bio, setBio] = useState("");
  const [location, setLocation] = useState("");
  const [website, setWebsite] = useState("");

  useEffect(() => {
    if (profileUser) {
      setName(profileUser.name || "");
      setUsernameVal(profileUser.username || "");
      setImage(profileUser.image || "");
      setBio(profileUser.bio || "");
      setLocation(profileUser.location || "");
      setWebsite(profileUser.website || "");
    }
  }, [profileUser]);

  const updateProfile = trpc.user.updateProfile.useMutation({
    onSuccess: () => {
      toast.success("Profile updated successfully");
      utils.user.byUsername.invalidate({ username });
      navigate({
        to: "/profile/$username",
        params: { username: usernameVal },
      });
    },
    onError: (error) => {
      if (error.message?.includes("Username already taken")) {
        toast.error("This username is already in use");
      } else {
        toast.error(error.message || "Failed to update profile");
      }
    },
  });

  // Guard: only own profile
  if (!isLoading && session?.user?.id !== profileUser?.id) {
    navigate({ to: "/profile/$username", params: { username } });
    return null;
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!name.trim()) {
      toast.error("Name is required");
      return;
    }

    if (!usernameVal.trim()) {
      toast.error("Username is required");
      return;
    }

    if (!/^[a-z0-9_-]+$/.test(usernameVal)) {
      toast.error(
        "Username can only contain lowercase letters, numbers, _ and -",
      );
      return;
    }

    updateProfile.mutate({
      name: name.trim(),
      username: usernameVal.trim().toLowerCase(),
      image: image.trim() || undefined,
      bio: bio || undefined,
      location: location.trim() || undefined,
      website: website.trim() || undefined,
    });
  };

  if (isLoading) {
    return <div className="container max-w-2xl py-6">Loading...</div>;
  }

  return (
    <div className="container max-w-2xl py-6 space-y-6">
      <Button
        variant="ghost"
        onClick={() =>
          navigate({ to: "/profile/$username", params: { username } })
        }
      >
        <ArrowLeft className="h-4 w-4 mr-2" />
        Back to Profile
      </Button>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <User className="h-5 w-5" />
            Edit Profile
          </CardTitle>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Avatar Preview */}
            <div className="flex items-center gap-4">
              <Avatar className="h-20 w-20">
                <AvatarImage src={image} />
                <AvatarFallback className="text-2xl">
                  {name?.[0]}
                </AvatarFallback>
              </Avatar>
              <div className="flex-1 space-y-2">
                <Label htmlFor="image">Avatar URL</Label>
                <Input
                  id="image"
                  type="url"
                  value={image}
                  onChange={(e) => setImage(e.target.value)}
                  placeholder="https://example.com/avatar.jpg"
                  disabled={updateProfile.isPending}
                />
              </div>
            </div>

            {/* Name */}
            <div className="space-y-2">
              <Label htmlFor="name">Display Name *</Label>
              <Input
                id="name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Your display name"
                disabled={updateProfile.isPending}
                maxLength={100}
              />
            </div>

            {/* Username */}
            <div className="space-y-2">
              <Label htmlFor="username">Username *</Label>
              <div className="flex items-center gap-2">
                <span className="text-muted-foreground text-sm">@</span>
                <Input
                  id="username"
                  value={usernameVal}
                  onChange={(e) => setUsernameVal(e.target.value.toLowerCase())}
                  placeholder="username"
                  disabled={updateProfile.isPending}
                  maxLength={30}
                />
              </div>
              <p className="text-xs text-muted-foreground">
                Only lowercase letters, numbers, underscores, and hyphens
              </p>
            </div>

            {/* Bio */}
            <div className="space-y-2">
              <Label htmlFor="bio">Bio</Label>
              <RichTextEditor
                value={bio}
                onChange={setBio}
                placeholder="Tell community about yourself..."
                disabled={updateProfile.isPending}
                showCharacterCount={true}
                maxLength={500}
              />
            </div>

            {/* Location */}
            <div className="space-y-2">
              <Label htmlFor="location">Location</Label>
              <Input
                id="location"
                value={location}
                onChange={(e) => setLocation(e.target.value)}
                placeholder="City, Country"
                disabled={updateProfile.isPending}
                maxLength={100}
              />
            </div>

            {/* Website */}
            <div className="space-y-2">
              <Label htmlFor="website">Website</Label>
              <Input
                id="website"
                type="url"
                value={website}
                onChange={(e) => setWebsite(e.target.value)}
                placeholder="https://yourwebsite.com"
                disabled={updateProfile.isPending}
              />
            </div>

            {/* Actions */}
            <div className="flex justify-end gap-2 pt-4">
              <Button
                type="button"
                variant="ghost"
                onClick={() =>
                  navigate({ to: "/profile/$username", params: { username } })
                }
                disabled={updateProfile.isPending}
              >
                Cancel
              </Button>
              <Button type="submit" disabled={updateProfile.isPending}>
                {updateProfile.isPending ? "Saving..." : "Save Changes"}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
