// src/lib/components/shared/NotificationBell.svelte
<script lang="ts">
	import { Bell } from '@lucide/svelte';
	import { Button } from '$lib/components/ui/button';
	import * as DropdownMenu from '$lib/components/ui/dropdown-menu';
	import { createEventDispatcher } from 'svelte';

	type Notification = {
		id: string;
		title: string;
		body: string | null;
		read: boolean;
	};

	let {
		unreadCount = 0,
		loading = false,
		recentNotifications = []
	}: {
		unreadCount: number;
		loading: boolean;
		recentNotifications: Notification[];
	} = $props();

	const dispatch = createEventDispatcher();

	function markAsRead(notificationId: string) {
		dispatch('markAsRead', notificationId);
	}
</script>

<DropdownMenu.Root>
	<DropdownMenu.Trigger>
		<Button variant="outline" size="icon" class="relative inline-flex">
			<Bell class="size-5" />
			{#if unreadCount > 0}
				<span
					class="absolute -top-1 -right-1 flex h-4 min-w-[1rem] items-center justify-center rounded-full bg-red-500 px-1.5 text-[0.65rem] font-bold text-white"
				>
					{unreadCount}
				</span>
			{/if}
		</Button>
	</DropdownMenu.Trigger>

	<DropdownMenu.Content align="end" class="w-72">
		<DropdownMenu.Label class="font-semibold">Notifications</DropdownMenu.Label>
		<DropdownMenu.Separator />

		{#if loading}
			<div class="py-6 text-center text-sm text-muted-foreground">Loading...</div>
		{:else if recentNotifications.length === 0}
			<div class="py-6 text-center text-sm text-muted-foreground">No notifications yet</div>
		{:else}
			{#each recentNotifications as n (n.id)}
				<DropdownMenu.Item
					class="flex cursor-pointer flex-col gap-1"
					on:click={() => markAsRead(n.id)}
				>
					<div class="flex items-center justify-between">
						<p class="truncate text-sm font-medium">{n.title}</p>
						{#if !n.read}
							<span class="inline-block h-2 w-2 rounded-full bg-blue-500"></span>
						{/if}
					</div>
					{#if n.body}
						<p class="line-clamp-2 text-xs text-muted-foreground">{n.body}</p>
					{/if}
				</DropdownMenu.Item>
			{/each}
		{/if}

		<DropdownMenu.Separator />
		<DropdownMenu.Item
			class="justify-center text-center text-sm font-medium text-primary hover:bg-transparent hover:text-primary/80"
			on:click={() => (window.location.href = '/notifications')}
		>
			<a href="/notifications">View all notifications →</a>
		</DropdownMenu.Item>
	</DropdownMenu.Content>
</DropdownMenu.Root>

// src/components/shared/NotificationBell.tsx
import { Link } from '@tanstack/react-router'
import { Button } from '~/components/ui/button'
import { Badge } from '~/components/ui/badge'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '~/components/ui/popover'
import { Bell, CheckCheck, ExternalLink } from 'lucide-react'
import { trpc } from '~/lib/trpc'
import { toast } from 'sonner'
import { formatDistanceToNow } from 'date-fns'
import { cn } from '~/lib/utils'

export default function NotificationBell() {
  const utils = trpc.useUtils()

  const { data: unreadData } = trpc.notifications.countUnread.useQuery(undefined, {
    refetchInterval: 30000, // Poll every 30 seconds
  })

  const { data, isLoading } = trpc.notifications.getAll.useInfiniteQuery(
    { limit: 5 },
    { getNextPageParam: (lastPage) => lastPage.nextCursor ?? undefined }
  )

  const markAllAsRead = trpc.notifications.markAllAsRead.useMutation({
    onSuccess: () => {
      utils.notifications.getAll.invalidate()
      utils.notifications.countUnread.invalidate()
      toast.success('All notifications marked as read')
    },
  })

  const markAsRead = trpc.notifications.markAsRead.useMutation({
    onSuccess: () => {
      utils.notifications.getAll.invalidate()
      utils.notifications.countUnread.invalidate()
    },
  })

  const notifications = data?.pages.flatMap((page) => page.items).slice(0, 5) ?? []
  const unreadCount = unreadData?.count || 0

  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button variant="ghost" size="icon" className="relative">
          <Bell className="h-5 w-5" />
          {unreadCount > 0 && (
            <Badge
              variant="destructive"
              className="absolute -top-1 -right-1 h-5 w-5 p-0 flex items-center justify-center text-xs"
            >
              {unreadCount > 99 ? '99+' : unreadCount}
            </Badge>
          )}
        </Button>
      </PopoverTrigger>

      <PopoverContent className="w-80 p-0" align="end">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b">
          <h3 className="font-semibold">Notifications</h3>
          {unreadCount > 0 && (
            <Button
              size="sm"
              variant="ghost"
              onClick={() => markAllAsRead.mutate()}
              disabled={markAllAsRead.isPending}
              className="text-xs h-7"
            >
              <CheckCheck className="h-3 w-3 mr-1" />
              Mark all read
            </Button>
          )}
        </div>

        {/* Notifications */}
        <div className="max-h-96 overflow-y-auto">
          {isLoading ? (
            <div className="p-4 text-center text-sm text-muted-foreground">
              Loading...
            </div>
          ) : notifications.length === 0 ? (
            <div className="p-8 text-center">
              <Bell className="h-8 w-8 mx-auto mb-2 text-muted-foreground" />
              <p className="text-sm text-muted-foreground">No notifications</p>
            </div>
          ) : (
            <div className="divide-y">
              {notifications.map((notif) => (
                <div
                  key={notif.id}
                  className={cn(
                    'flex items-start gap-3 p-4 hover:bg-muted transition-colors',
                    !notif.read && 'bg-accent/30'
                  )}
                >
                  {/* Unread indicator */}
                  <div className="mt-1.5 flex-shrink-0">
                    {!notif.read ? (
                      <div className="h-2 w-2 rounded-full bg-primary" />
                    ) : (
                      <div className="h-2 w-2 rounded-full bg-transparent" />
                    )}
                  </div>

                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium line-clamp-1">{notif.title}</p>
                    <p className="text-xs text-muted-foreground line-clamp-2 mt-0.5">
                      {notif.message}
                    </p>
                    <p className="text-xs text-muted-foreground mt-1">
                      {formatDistanceToNow(new Date(notif.createdAt), { addSuffix: true })}
                    </p>
                  </div>

                  <div className="flex flex-col gap-1 flex-shrink-0">
                    <Link to={notif.link as any}>
                      <Button variant="ghost" size="icon" className="h-6 w-6">
                        <ExternalLink className="h-3 w-3" />
                      </Button>
                    </Link>

                    {!notif.read && (
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-6 w-6"
                        onClick={() => markAsRead.mutate({ id: notif.id })}
                        disabled={markAsRead.isPending}
                      >
                        <CheckCheck className="h-3 w-3" />
                      </Button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="border-t p-3">
          <Link to="/notifications" className="block">
            <Button variant="outline" size="sm" className="w-full">
              View all notifications
            </Button>
          </Link>
        </div>
      </PopoverContent>
    </Popover>
  )
}
