// src/routes/(client-area)/notifications/+page.svelte
<script lang="ts">
	import { onDestroy, onMount } from 'svelte';
	import { toast } from 'svelte-sonner';

	import { Button } from '$components/ui/button';
	import * as Card from '$components/ui/card';
	import { Skeleton } from '$components/ui/skeleton';
	import { createTRPC } from '$lib/trpc';

	const trpc = createTRPC();

	type Notification = Awaited<ReturnType<typeof trpc.notifications.getAll.query>>['items'][number];

	let notifications = $state<Notification[]>([]);
	let loading = $state(true);
	let loadingMore = $state(false);
	let nextCursor = $state<string | null>(null);

	let observer: IntersectionObserver;
	let loadMoreTrigger: HTMLDivElement;

	async function loadNotifications(cursor?: string) {
		if (loadingMore || loading) return;

		try {
			if (cursor) loadingMore = true;
			const res = await trpc.notifications.getAll.query({ limit: 10, cursor });
			notifications = [...notifications, ...res.items];
			nextCursor = res.nextCursor;
		} catch {
			toast.error('Failed to load notifications');
		} finally {
			loading = false;
			loadingMore = false;
		}
	}

	async function markAsRead(id: string) {
		try {
			await trpc.notifications.markAsRead.mutate({ id });
			notifications = notifications.map((n) => (n.id === id ? { ...n, read: true } : n));
		} catch {
			toast.error('Failed to mark as read');
		}
	}

	async function markAllAsRead() {
		try {
			await trpc.notifications.markAllAsRead.mutate();
			notifications = notifications.map((n) => ({ ...n, read: true }));
			toast.success('All notifications marked as read');
		} catch {
			toast.error('Failed to mark all as read');
		}
	}

	onMount(() => loadNotifications());

	$effect(() => {
		if (loadMoreTrigger && nextCursor) {
			if (observer) observer.disconnect();
			observer = new IntersectionObserver((entries) => {
				if (entries[0].isIntersecting && nextCursor) {
					loadNotifications(nextCursor);
				}
			});
			observer.observe(loadMoreTrigger);
		}
	});

	onDestroy(() => {
		if (observer) observer.disconnect();
	});
</script>

<div class="container mx-auto max-w-3xl py-8">
	<div class="mb-6 flex items-center justify-between">
		<h1 class="text-3xl font-bold">Notifications</h1>
		{#if notifications.some((n) => !n.read)}
			<Button size="sm" variant="outline" on:click={markAllAsRead}>Mark all as read</Button>
		{/if}
	</div>

	{#if loading}
		<!-- Initial Skeleton Loader -->
		<div class="space-y-4">
			{#each Array(3) as _}
				<Card.Root>
					<Card.Content class="flex items-center justify-between p-4">
						<div>
							<Skeleton class="mb-2 h-4 w-64" />
							<Skeleton class="h-3 w-24" />
						</div>
						<Skeleton class="h-8 w-28 rounded-md" />
					</Card.Content>
				</Card.Root>
			{/each}
		</div>
	{:else if notifications.length === 0}
		<p class="text-muted-foreground">No notifications yet.</p>
	{:else}
		<div class="space-y-4">
			{#each notifications as n}
				<Card.Root class={!n.read ? 'bg-accent/40' : ''}>
					<Card.Content class="flex items-center justify-between p-4">
						<div>
							<p>{n.message}</p>
							<p class="text-sm text-muted-foreground">
								{new Date(n.createdAt).toLocaleString()}
							</p>
						</div>
						{#if !n.read}
							<Button
								size="sm"
								variant="outline"
								on:click={(e) => {
									e.stopPropagation();
									markAsRead(n.id);
								}}
							>
								Mark as Read
							</Button>
						{/if}
					</Card.Content>
				</Card.Root>
			{/each}
		</div>
	{/if}

	<!-- Infinite Scroll Loader -->
	<div class="flex justify-center py-4" bind:this={loadMoreTrigger}>
		{#if loadingMore}
			<div class="w-full space-y-4">
				{#each Array(2) as _}
					<Card.Root>
						<Card.Content class="flex items-center justify-between p-4">
							<div>
								<Skeleton class="mb-2 h-4 w-64" />
								<Skeleton class="h-3 w-24" />
							</div>
							<Skeleton class="h-8 w-28 rounded-md" />
						</Card.Content>
					</Card.Root>
				{/each}
			</div>
		{/if}
	</div>
</div>

// src/routes/_client/notifications.tsx
import { createFileRoute, Link } from '@tanstack/react-router'
import { useEffect, useRef, useCallback } from 'react'
import { Button } from '~/components/ui/button'
import { Card, CardContent } from '~/components/ui/card'
import { Skeleton } from '~/components/ui/skeleton'
import { trpc } from '~/lib/trpc'
import { toast } from 'sonner'
import { cn } from '~/lib/utils'

export const Route = createFileRoute('/_client/notifications')({
  component: NotificationsPage,
})

function NotificationsPage() {
  const utils = trpc.useUtils()
  const loadMoreRef = useRef<HTMLDivElement>(null)

  const {
    data,
    isLoading,
    fetchNextPage,
    hasNextPage,
    isFetchingNextPage,
  } = trpc.notifications.getAll.useInfiniteQuery(
    { limit: 10 },
    {
      getNextPageParam: (lastPage) => lastPage.nextCursor ?? undefined,
    }
  )

  const notifications = data?.pages.flatMap((page) => page.items) ?? []
  const hasUnread = notifications.some((n: any) => !n.read)

  const markAsRead = trpc.notifications.markAsRead.useMutation({
    onSuccess: (data, variables) => {
      // Optimistic-like update using exact cache invalidation
      utils.notifications.getAll.invalidate()
    },
    onError: () => toast.error('Failed to mark as read'),
  })

  const markAllAsRead = trpc.notifications.markAllAsRead.useMutation({
    onSuccess: () => {
      utils.notifications.getAll.invalidate()
      toast.success('All notifications marked as read')
    },
    onError: () => toast.error('Failed to mark all as read'),
  })

  const handleObserver = useCallback(
    (entries: IntersectionObserverEntry[]) => {
      if (entries[0].isIntersecting && hasNextPage && !isFetchingNextPage) {
        fetchNextPage()
      }
    },
    [fetchNextPage, hasNextPage, isFetchingNextPage]
  )

  useEffect(() => {
    const element = loadMoreRef.current
    if (!element) return

    const observer = new IntersectionObserver(handleObserver, {
      threshold: 0.1,
    })

    observer.observe(element)

    return () => observer.disconnect()
  }, [handleObserver])

  return (
    <div className="container mx-auto max-w-3xl py-8">
      <div className="mb-6 flex items-center justify-between">
        <h1 className="text-3xl font-bold">Notifications</h1>
        {hasUnread && (
          <Button size="sm" variant="outline" onClick={() => markAllAsRead.mutate()}>
            Mark all as read
          </Button>
        )}
      </div>

      {isLoading ? (
        <div className="space-y-4">
          {Array.from({ length: 3 }).map((_, i) => (
            <Card key={i}>
              <CardContent className="flex items-center justify-between p-4">
                <div>
                  <Skeleton className="mb-2 h-4 w-64" />
                  <Skeleton className="h-3 w-24" />
                </div>
                <Skeleton className="h-8 w-28 rounded-md" />
              </CardContent>
            </Card>
          ))}
        </div>
      ) : notifications.length === 0 ? (
        <p className="text-muted-foreground">No notifications yet.</p>
      ) : (
        <div className="space-y-4">
          {notifications.map((n: any) => (
            <Card key={n.id} className={cn(!n.read ? 'bg-accent/40' : '')}>
              <CardContent className="flex items-center justify-between p-4">
                <div>
                  <p>{n.message}</p>
                  <p className="text-sm text-muted-foreground">
                    {new Date(n.createdAt).toLocaleString()}
                  </p>
                </div>
                {!n.read && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={(e) => {
                      e.stopPropagation()
                      markAsRead.mutate({ id: n.id })
                    }}
                  >
                    Mark as Read
                  </Button>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Infinite Scroll Loader */}
      <div className="flex justify-center py-4" ref={loadMoreRef}>
        {isFetchingNextPage && (
          <div className="w-full space-y-4">
            {Array.from({ length: 2 }).map((_, i) => (
              <Card key={i}>
                <CardContent className="flex items-center justify-between p-4">
                  <div>
                    <Skeleton className="mb-2 h-4 w-64" />
                    <Skeleton className="h-3 w-24" />
                  </div>
                  <Skeleton className="h-8 w-28 rounded-md" />
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
