// src/routes/_landing/terms.tsx
import { createFileRoute } from '@tanstack/react-router'


export const Route = createFileRoute('/_landing/terms')({
  component: TermsPage,
})

function TermsPage() {
  return (
    
      <div className="mx-auto max-w-4xl px-4 py-20 sm:px-6 lg:px-8">
	<h1 className="font-heading mb-4 text-4xl font-bold text-foreground">Terms of Service</h1>
	<p className="mb-8 text-muted-foreground">Last updated: January 1, 2024</p>

	<div className="prose prose-lg max-w-none">
		<div className="space-y-8 leading-relaxed text-muted-foreground">
			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">
					1. Acceptance of Terms
				</h2>
				<p>
					By accessing and using Foreum ("Service"), you accept and agree to be bound by the terms
					and provision of this agreement. If you do not agree to these Terms of Service, please do
					not use the Service.
				</p>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">
					2. Description of Service
				</h2>	
				<p>
					Foreum provides a forum platform that allows users to create and manage online
					communities. The Service includes features for discussion threads, user management,
					moderation tools, and community engagement.
				</p>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">3. User Accounts</h2>
				<p className="mb-4">
					To use certain features of the Service, you must register for an account. When you
					register, you agree to:
				</p>
				<ul className="list-disc space-y-2 pl-6">
					<li>Provide accurate, current, and complete information</li>
					<li>Maintain and promptly update your account information</li>
					<li>Maintain the security of your password and account</li>
					<li>Accept responsibility for all activities under your account</li>
					<li>Notify us immediately of any unauthorized use of your account</li>
				</ul>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">4. Acceptable Use</h2>
				<p className="mb-4">You agree not to use the Service to:</p>
				<ul className="list-disc space-y-2 pl-6">
					<li>Violate any laws or regulations</li>
					<li>Post harmful, threatening, abusive, or harassing content</li>
					<li>Impersonate any person or entity</li>
					<li>Distribute spam or unsolicited messages</li>
					<li>Interfere with or disrupt the Service or servers</li>
					<li>Attempt to gain unauthorized access to any systems</li>
					<li>Collect or store personal data about other users</li>
				</ul>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">5. Content</h2>
				<p className="mb-4">
					You retain ownership of content you post to the Service. By posting content, you grant
					Foreum a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, and
					display your content in connection with the Service.
				</p>
				<p>
					You are solely responsible for your content and the consequences of posting it. We reserve
					the right to remove any content that violates these Terms or is otherwise objectionable.
				</p>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">6. Payment Terms</h2>
				<p className="mb-4">
					Paid subscriptions are billed in advance on a monthly or annual basis. You agree to pay
					all fees associated with your subscription plan.
				</p>
				<ul className="list-disc space-y-2 pl-6">
					<li>Fees are non-refundable except as required by law</li>
					<li>We may change pricing with 30 days notice</li>
					<li>You can cancel your subscription at any time</li>
					<li>Cancellations take effect at the end of the billing period</li>
				</ul>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">7. Termination</h2>
				<p>
					We may terminate or suspend your account and access to the Service immediately, without
					prior notice, for conduct that we believe violates these Terms or is harmful to other
					users, us, or third parties, or for any other reason.
				</p>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">8. Disclaimers</h2>
				<p>
					THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
					WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE.
				</p>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">
					9. Limitation of Liability
				</h2>
				<p>
					TO THE MAXIMUM EXTENT PERMITTED BY LAW, FOREUM SHALL NOT BE LIABLE FOR ANY INDIRECT,
					INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR
					REVENUES.
				</p>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">
					10. Changes to Terms
				</h2>
				<p>
					We reserve the right to modify these Terms at any time. We will notify users of any
					material changes via email or through the Service. Your continued use of the Service after
					changes constitutes acceptance of the new Terms.
				</p>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">11. Contact</h2>
				<p>If you have questions about these Terms, please contact us at legal@foreum.com.</p>
			</section>
		</div>
	</div>
</div>

  )
}

// src/routes/(landing)/terms/+page.svelte
<svelte:head>
	<title>Terms of Service - Foreum</title>
	<meta name="description" content="Terms of Service for Foreum forum platform." />
</svelte:head>

<div class="mx-auto max-w-4xl px-4 py-20 sm:px-6 lg:px-8">
	<h1 class="font-heading mb-4 text-4xl font-bold text-foreground">Terms of Service</h1>
	<p class="mb-8 text-muted-foreground">Last updated: January 1, 2024</p>

	<div class="prose prose-lg max-w-none">
		<div class="space-y-8 leading-relaxed text-muted-foreground">
			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">
					1. Acceptance of Terms
				</h2>
				<p>
					By accessing and using Foreum ("Service"), you accept and agree to be bound by the terms
					and provision of this agreement. If you do not agree to these Terms of Service, please do
					not use the Service.
				</p>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">
					2. Description of Service
				</h2>
				<p>
					Foreum provides a forum platform that allows users to create and manage online
					communities. The Service includes features for discussion threads, user management,
					moderation tools, and community engagement.
				</p>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">3. User Accounts</h2>
				<p class="mb-4">
					To use certain features of the Service, you must register for an account. When you
					register, you agree to:
				</p>
				<ul class="list-disc space-y-2 pl-6">
					<li>Provide accurate, current, and complete information</li>
					<li>Maintain and promptly update your account information</li>
					<li>Maintain the security of your password and account</li>
					<li>Accept responsibility for all activities under your account</li>
					<li>Notify us immediately of any unauthorized use of your account</li>
				</ul>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">4. Acceptable Use</h2>
				<p class="mb-4">You agree not to use the Service to:</p>
				<ul class="list-disc space-y-2 pl-6">
					<li>Violate any laws or regulations</li>
					<li>Post harmful, threatening, abusive, or harassing content</li>
					<li>Impersonate any person or entity</li>
					<li>Distribute spam or unsolicited messages</li>
					<li>Interfere with or disrupt the Service or servers</li>
					<li>Attempt to gain unauthorized access to any systems</li>
					<li>Collect or store personal data about other users</li>
				</ul>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">5. Content</h2>
				<p class="mb-4">
					You retain ownership of content you post to the Service. By posting content, you grant
					Foreum a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, and
					display your content in connection with the Service.
				</p>
				<p>
					You are solely responsible for your content and the consequences of posting it. We reserve
					the right to remove any content that violates these Terms or is otherwise objectionable.
				</p>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">6. Payment Terms</h2>
				<p class="mb-4">
					Paid subscriptions are billed in advance on a monthly or annual basis. You agree to pay
					all fees associated with your subscription plan.
				</p>
				<ul class="list-disc space-y-2 pl-6">
					<li>Fees are non-refundable except as required by law</li>
					<li>We may change pricing with 30 days notice</li>
					<li>You can cancel your subscription at any time</li>
					<li>Cancellations take effect at the end of the billing period</li>
				</ul>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">7. Termination</h2>
				<p>
					We may terminate or suspend your account and access to the Service immediately, without
					prior notice, for conduct that we believe violates these Terms or is harmful to other
					users, us, or third parties, or for any other reason.
				</p>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">8. Disclaimers</h2>
				<p>
					THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.
					WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE.
				</p>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">
					9. Limitation of Liability
				</h2>
				<p>
					TO THE MAXIMUM EXTENT PERMITTED BY LAW, FOREUM SHALL NOT BE LIABLE FOR ANY INDIRECT,
					INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR
					REVENUES.
				</p>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">
					10. Changes to Terms
				</h2>
				<p>
					We reserve the right to modify these Terms at any time. We will notify users of any
					material changes via email or through the Service. Your continued use of the Service after
					changes constitutes acceptance of the new Terms.
				</p>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">11. Contact</h2>
				<p>If you have questions about these Terms, please contact us at legal@foreum.com.</p>
			</section>
		</div>
	</div>
</div>
