// src/routes/(client-area)/threads/new/+page.svelte
<script lang="ts">
	import { browser } from '$app/environment';
	import type { Content, Editor } from '@tiptap/core';
	import type { Transaction } from '@tiptap/pm/state';
	import { Edra, EdraToolbar, EdraBubbleMenu } from '$components/thread/edra/shadcn';
	import defaultContent from '$components/thread/edra/default_content';
	import DragHandle from '$components/thread/edra/drag-handle.svelte';

	import { ArrowLeft } from '@lucide/svelte';
	import { toast } from 'svelte-sonner';
	import { type Infer, superForm, type SuperValidated } from 'sveltekit-superforms';
	import { zodClient } from 'sveltekit-superforms/adapters';

	import { goto } from '$app/navigation';
	import { Button } from '$components/ui/button';
	import * as Form from '$components/ui/form';
	import { Input } from '$components/ui/input';
	import MultiSelect from '$components/ui/multi-select/multi-select.svelte';
	import * as Select from '$components/ui/select';
	import { threadSchema } from '$lib/schemas';
	import { createTRPC } from '$lib/trpc';

	let { data } = $props<{
		data: {
			form: SuperValidated<Infer<typeof threadSchema>>;
			message?: string;
		};
	}>();

	const form = superForm(data.form, {
		dataType: 'json',
		taintedMessage: null,
		validators: zodClient(threadSchema)
	});
	const { form: formData, errors, enhance } = form;

	const trpc = createTRPC();

	let tagOptions = $state<{ label: string; value: string }[]>([]);
	let categories = $state<Awaited<ReturnType<typeof trpc.category.list.query>>>([]);
	let creating = $state(false);

	// Load categories + tags
	$effect(() => {
		(async () => {
			const cats = await trpc.category.list.query();
			const fetchedTags = await trpc.tag.list.query();

			categories = cats;
			tagOptions = fetchedTags.map((t) => ({
				label: t.name,
				value: t.id
			}));
		})();
	});

	async function handleSubmit() {
		if (!$formData.title.trim() || editor?.isEmpty || !$formData.categoryId) {
			toast.error('Please fill in all required fields');
			return;
		}

		creating = true;
		try {
			const result = await trpc.thread.create.mutate({
				title: $formData.title,
				content: $formData.content,
				categoryId: $formData.categoryId,
				tags: $formData.tags
			});
			toast.success('Thread created successfully!');
			goto(`/threads/${result.id}`);
		} catch (err) {
			console.error(err);
			toast.error('Failed to create thread');
		} finally {
			creating = false;
		}
	}

	// Editor states
	let content = $state<Content>();
	let editor = $state<Editor>();
	let showToolBar = $state(true);
	let showSlashCommands = $state(true);
	let showLinkBubbleMenu = $state(true);
	let showTableBubbleMenu = $state(true);

	$effect(() => {
		$inspect('[DEBUG] Content', content);
		localStorage.setItem('edra-content', JSON.stringify(content));
	});

	if (browser) {
		const rawDataString = localStorage.getItem('edra-content');

		if (rawDataString === null) {
			content = defaultContent;
		} else {
			const rawData: Content = JSON.parse(rawDataString);
			content = rawData;
		}
		$formData.content = content;
	}

	function onUpdate(props: { editor: Editor; transaction: Transaction }) {
		content = props.editor.getJSON();
		$formData.content = content;
	}
</script>

<div class="container mx-auto max-w-4xl px-4 py-8">
	<a href="/threads" class="mb-6 inline-flex items-center">
		<Button variant="ghost" size="sm">
			<ArrowLeft class="mr-2 size-4" /> Back to Threads
		</Button>
	</a>

	<h1 class="mb-6 text-3xl font-bold">Create New Thread</h1>

	<form onsubmit={handleSubmit} class="space-y-6">
		<!-- Title -->
		<Form.Field {form} name="title">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Title</Form.Label>
					<Input {...props} bind:value={$formData.title} />
				{/snippet}
			</Form.Control>
			<Form.FieldErrors />
		</Form.Field>

		<!-- Tags + Category -->
		<div class="flex flex-col space-y-2">
			<Form.Field {form} name="tags">
				<Form.Control>
					{#snippet children()}
						<Form.Label>Tags</Form.Label>
						<MultiSelect
							options={tagOptions}
							value={$formData.tags?.map((t) => ({ value: t, label: t })) ?? []}
							onChange={(v) => {
								$formData.tags = v.map((t) => t.value);
							}}
							placeholder="Select tags..."
							creatable
						/>
					{/snippet}
				</Form.Control>
				<Form.FieldErrors />
			</Form.Field>

			<Form.Field {form} name="categoryId">
				<Form.Control>
					<Select.Root type="single" bind:value={$formData.categoryId}>
						<Select.Trigger
							class="w-full focus-visible:border-indigo-500 focus-visible:ring-indigo-500/20 dark:focus-visible:ring-indigo-500/40"
						>
							{$formData.categoryId
								? categories.find((cat) => cat.id === $formData.categoryId)?.name
								: 'Select a category'}
						</Select.Trigger>
						<Select.Content>
							{#each categories as category (category.id)}
								<Select.Item value={category.id}>{category.name}</Select.Item>
							{/each}
						</Select.Content>
					</Select.Root>
				</Form.Control>
				<Form.FieldErrors />
			</Form.Field>
		</div>

		<!-- Content -->
		<Form.Field {form} name="content">
			<Form.Control>
				{#snippet children({ props })}
					<Form.Label>Content</Form.Label>
					<!-- <Textarea {...props} class="mb-2" bind:value={$formData.content} /> -->

					{#if editor && showToolBar}
						<div class="rounded-t border-x border-t">
							<!-- Default Edra toolbar -->
							<div class="overflow-x-auto">
								<div class="min-w-full">
									<EdraToolbar class="flex-nowrap px-2 py-1" {editor} />
								</div>
							</div>
						</div>
						<!-- Add bubble menu -->
						<EdraBubbleMenu {editor} />
						<DragHandle {editor} />
					{/if}
					<div class="rounded-b border">
						<Edra
							class="h-80 overflow-auto"
							bind:editor
							{content}
							{showSlashCommands}
							{showLinkBubbleMenu}
							{showTableBubbleMenu}
							{onUpdate}
						/>
					</div>
				{/snippet}
			</Form.Control>
			<Form.FieldErrors />
		</Form.Field>

		<div class="flex justify-end gap-4">
			<Button type="button" variant="outline" onclick={() => goto('/threads')}>Cancel</Button>
			<Button type="submit" disabled={creating}>
				{creating ? 'Creating...' : 'Create Thread'}
			</Button>
		</div>
	</form>
</div>

// src/routes/_client/threads/new.tsx
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useForm } from '@tanstack/react-form'
import { z } from 'zod'
import { trpc } from '~/lib/trpc'
import { toast } from 'sonner'

import { PlateEditor } from '~/components/editor/plate-editor'
import MultipleSelector from '~/components/ui/multi-select'
import { Input } from '~/components/ui/input'
import { Label } from '~/components/ui/label'
import { Button } from '~/components/ui/button'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '~/components/ui/select'

export const Route = createFileRoute('/_client/threads/new')({
  component: NewThreadPage,
})

const threadSchema = z.object({
  title: z.string().min(1, 'Title is required').max(200, 'Title is too long'),
  content: z.string().refine((val) => {
      try {
          const parsed = JSON.parse(val);
          if (!parsed || !Array.isArray(parsed)) return false;
          // Just extremely simplistic checking that there is text
          const hasText = parsed.some(block => block.children?.some((child: any) => child.text !== undefined));
          // Plate sometimes yields an array with empty paragraphs `[{type: 'p', children:[{text:''}]}]`
          const isEmpty = parsed.length === 1 && parsed[0].type === 'p' && parsed[0].children?.length === 1 && parsed[0].children[0].text === '';
          return hasText && !isEmpty;
      } catch (err) {
          return false;
      }
  }, { message: 'Content is required' }),
  categoryId: z.string().min(1, 'Please select a category'),
  tags: z.array(z.string()).optional(),
})

function NewThreadPage() {
  const navigate = useNavigate()
  const utils = trpc.useUtils()
  
  const { data: categories, isLoading: categoriesLoading } = trpc.category.list.useQuery()
  
  const createThread = trpc.thread.create.useMutation({
    onSuccess: (data) => {
      toast.success('Thread created successfully')
      utils.thread.list.invalidate()
      navigate({ to: '/threads/thread/$id', params: { id: data.id } })
    },
    onError: (error) => {
      toast.error(error.message || 'Failed to create thread')
    },
  })

  const form = useForm({
    defaultValues: {
      title: '',
      content: JSON.stringify([{ type: 'p', children: [{ text: '' }] }]),
      categoryId: '',
      tags: [] as string[],
    },
    validators: {
      onChange: threadSchema,
    },
    onSubmit: async ({ value }) => {
      await createThread.mutateAsync(value)
    },
  })

  return (
    <div className="max-w-4xl mx-auto p-6 space-y-8 fade-in animate-in">
      <div className="space-y-1">
        <h1 className="text-3xl font-bold tracking-tight">Create New Thread</h1>
        <p className="text-muted-foreground">
          Start a new discussion in the community
        </p>
      </div>
      
      <form
        onSubmit={(e) => {
          e.preventDefault()
          e.stopPropagation()
          form.handleSubmit()
        }}
        className="space-y-6 bg-card  p-6 shadow-sm"
      >
        <form.Field
          name="title"
          children={(field) => (
            <div className="space-y-2">
              <Label htmlFor={field.name}>Title</Label>
              <Input
                id={field.name}
                name={field.name}
                value={field.state.value}
                onBlur={field.handleBlur}
                onChange={(e) => field.handleChange(e.target.value)}
                placeholder="Enter a descriptive title"
                disabled={createThread.isPending}
                maxLength={200}
                className="bg-background"
              />
              <div className="flex justify-between items-start">
                  {field.state.meta.errors ? (
                    <em role="alert" className="text-xs text-destructive font-medium">
                      {field.state.meta.errors.join(', ')}
                    </em>
                  ) : <span />}
                  <span className="text-xs text-muted-foreground ml-auto">
                    {field.state.value.length}/200
                  </span>
              </div>
            </div>
          )}
        />

        <form.Field
          name="categoryId"
          children={(field) => (
            <div className="space-y-2">
              <Label htmlFor={field.name}>Category</Label>
              <Select
                value={field.state.value}
                onValueChange={field.handleChange}
                disabled={categoriesLoading || createThread.isPending}
              >
                <SelectTrigger className="bg-background">
                  <SelectValue placeholder="Select a category" />
                </SelectTrigger>
                <SelectContent>
                  {categories?.map((category) => (
                    <SelectItem key={category.id} value={category.id}>
                      {category.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {field.state.meta.errors ? (
                <em role="alert" className="text-xs text-destructive font-medium">
                  {field.state.meta.errors.join(', ')}
                </em>
              ) : null}
            </div>
          )}
        />

        <form.Field
          name="content"
          children={(field) => (
            <div className="space-y-2">
              <Label htmlFor={field.name}>Content</Label>
              <div className="border rounded-md overflow-hidden focus-within:ring-2 focus-within:ring-ring focus-within:ring-offset-2 transition-shadow">
                <PlateEditor
                  value={(() => {
                    try {
                      return JSON.parse(field.state.value)
                    } catch (e) {
                      return [{ type: 'p', children: [{ text: '' }] }]
                    }
                  })()}
                  onChange={(val) => field.handleChange(JSON.stringify(val))}
                  disabled={createThread.isPending}
                />
              </div>
              {field.state.meta.errors ? (
                <em role="alert" className="text-xs text-destructive font-medium">
                  {field.state.meta.errors.join(', ')}
                </em>
              ) : null}
            </div>
          )}
        />

        <form.Field
          name="tags"
          children={(field) => (
            <div className="space-y-2">
              <Label htmlFor={field.name}>Tags (optional)</Label>
              <MultipleSelector
                value={(field.state.value || []).map((t: string) => ({ label: t, value: t }))}
                onChange={(options) => field.handleChange(options.map((o) => o.value))}
                placeholder="Select tags"
                creatable
                emptyIndicator={<p className="text-center text-sm py-2">No predefined tags found.</p>}
                className="bg-background"
              />
              <p className="text-xs text-muted-foreground pt-1">
                Type and press enter to add tags. Separate items to help others discover your thread.
              </p>
            </div>
          )}
        />

        <div className="flex justify-end gap-3 pt-6 border-t mt-6">
          <Button
            type="button"
            variant="ghost"
            onClick={() => navigate({ to: '/threads' })}
            disabled={createThread.isPending}
          >
            Cancel
          </Button>
          <form.Subscribe
            selector={(state) => [state.canSubmit, state.isSubmitting]}
            children={([canSubmit, isSubmitting]) => (
              <Button type="submit" disabled={!canSubmit || createThread.isPending}>
                {createThread.isPending ? 'Creating...' : 'Create Thread'}
              </Button>
            )}
          />
        </div>
      </form>
    </div>
  )
}
