// src/routes/(auth)/reset-password/+page.svelte
<script lang="ts">
	import { superForm } from 'sveltekit-superforms';
	import { zodClient } from 'sveltekit-superforms/adapters';
	import { resetPasswordSchema } from '$lib/schemas';
	import { authClient } from '$lib/auth-client';
	import * as Form from '$components/ui/form';
	import { Input } from '$components/ui/input';
	import { Button } from '$components/ui/button';
	import * as Alert from '$components/ui/alert';
	import { goto } from '$app/navigation';
	import { page } from '$app/state';
	import * as Card from '$components/ui/card';

	let loading = $state(false);
	let serverError = $state<string | null>(null);
	let successMessage = $state<string | null>(null);

	let { data } = $props<{
		data: any;
	}>();
	const token = page.url.searchParams.get('token');
	const form = superForm(data.form, { validators: zodClient(resetPasswordSchema) });
	const { form: formData, enhance } = form;

	async function onSubmit() {
		serverError = null;
		successMessage = null;
		if (!token) {
			serverError = 'Invalid or expired reset link.';
			return;
		}
		try {
			await authClient.resetPassword(
				{
					newPassword: $formData.password,
					token
				},
				{
					onSuccess: async () => {
						successMessage = 'Password reset successful!';
						setTimeout(() => goto('/login'), 2000);
					}
				}
			);
		} catch (err: any) {
			serverError = err.message || 'Something went wrong';
		} finally {
			loading = false;
		}
	}
</script>

<Card.Root class="w-full max-w-md">
	<Card.Header class="space-y-1">
		<Card.Title class="text-center text-2xl font-bold">Reset Password</Card.Title>
		<Card.Description class="text-center">
			Enter your new password to reset your account
		</Card.Description>
	</Card.Header>
	<Card.Content class="space-y-4">
		{#if serverError}
			<Alert.Root variant="destructive"
				><Alert.Description>{serverError}</Alert.Description></Alert.Root
			>
		{/if}
		{#if successMessage}
			<Alert.Root><Alert.Description>{successMessage}</Alert.Description></Alert.Root>
		{/if}

		<form method="POST" use:enhance on:submit|preventDefault={onSubmit}>
			<Form.Field {form} name="password">
				<Form.Control
					><Form.Label>New Password</Form.Label>
					<Input type="password" placeholder="Enter new password" />
				</Form.Control><Form.FieldErrors />
			</Form.Field>

			<Form.Field {form} name="confirmPassword">
				<Form.Control>
					<Form.Label>Confirm Password</Form.Label>
					<Input type="password" placeholder="Confirm new password" /></Form.Control
				>
				<Form.FieldErrors />
			</Form.Field>

			<Button class="w-full" disabled={loading}>
				{loading ? 'Resetting...' : 'Reset Password'}
			</Button>
		</form>
	</Card.Content>
	<Card.Footer class="flex flex-col py-4 text-sm text-muted-foreground">
		<div class="flex w-full justify-between">
			<a href="/login" class="hover:text-primary">Remember Your Password?</a>
			<a href="/signup" class="hover:text-primary">Don’t have an Account?</a>
		</div>
	</Card.Footer>
</Card.Root>

// src/routes/_auth/reset-password.tsx


import { Suspense, useState } from "react";
import { createFileRoute, Link, useNavigate, useSearch } from "@tanstack/react-router";
import { useForm } from "@tanstack/react-form";
import { toast } from "sonner";
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
  FieldError,
} from "~/components/ui/field";
import { Input } from "~/components/ui/input";
import { Button } from "~/components/ui/button";
import {
  resetPasswordSchema,
} from "~/lib/schemas";
import { resetPassword } from "~/lib/auth-client";
import { KeyRound } from "lucide-react";
import { Spinner } from "~/components/ui/spinner";
import { Alert, AlertDescription, AlertTitle } from "~/components/ui/alert";



function ResetPasswordContent() {
  const [isLoading, setIsLoading] = useState(false);
  const [serverError, setServerError] = useState<string | null>(null);
  const navigate = useNavigate();
  const search = useSearch({ strict: false }) as any;
  const token = search.token;

  const form = useForm({
    defaultValues: {
      password: "",
      confirmPassword: "",
    },
    validators: {
      onSubmit: resetPasswordSchema,
    },
    onSubmit: async ({ value }) => {
      if (!token) {
        setServerError("Invalid reset token");
        toast.error("Invalid reset token");
        return;
      }

      setIsLoading(true);
      setServerError(null);

      try {
        const result = await resetPassword({
          newPassword: value.password,
          token,
        });

        if (result.error) {
          setServerError(result.error.message || "Failed to reset password");
          toast.error("Failed to reset password");
        } else {
          toast.success("Password reset successfully!");
          navigate({ to: "/sign-in" });
        }
      } catch (error) {
        setServerError("An unexpected error occurred");
        toast.error("An unexpected error occurred");
      } finally {
        setIsLoading(false);
      }
    },
  });
  return (
    <div className="flex flex-col gap-6">
      <FieldGroup>
        <div className="flex flex-col gap-2">
          <KeyRound className="h-8 w-8 text-primary" />
          <h1 className="text-2xl font-bold">Set new password</h1>
          <p className="text-muted-foreground text-sm">
            Enter your new password below
          </p>
        </div>

        {serverError && (
          <FieldError className="text-center">
            <Alert variant="destructive">
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>{serverError}</AlertDescription>
            </Alert>
          </FieldError>
        )}

        <form
          onSubmit={(e) => {
            e.preventDefault();
            e.stopPropagation();
            form.handleSubmit();
          }}
          className="flex flex-col gap-6"
        >
          <form.Field
            name="password"
            children={(field) => {
              const isInvalid =
                field.state.meta.isTouched && !field.state.meta.isValid;
              return (
                <Field data-invalid={isInvalid}>
                  <FieldLabel htmlFor={field.name}>New Password</FieldLabel>
                  <Input
                    id={field.name}
                    name={field.name}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                    type="password"
                    placeholder="•••••••••"
                    aria-invalid={isInvalid}
                    disabled={isLoading}
                  />
                  {isInvalid && (
                    <FieldError errors={field.state.meta.errors} />
                  )}
                </Field>
              );
            }}
          />

          <form.Field
            name="confirmPassword"
            children={(field) => {
              const isInvalid =
                field.state.meta.isTouched && !field.state.meta.isValid;
              return (
                <Field data-invalid={isInvalid}>
                  <FieldLabel htmlFor={field.name}>Confirm Password</FieldLabel>
                  <Input
                    id={field.name}
                    name={field.name}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                    type="password"
                    placeholder="•••••••••"
                    aria-invalid={isInvalid}
                    disabled={isLoading}
                  />
                  {isInvalid && (
                    <FieldError errors={field.state.meta.errors} />
                  )}
                </Field>
              );
            }}
          />

          <Field>
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading && <Spinner className="mr-2 h-4 w-4" />}
              Reset Password
            </Button>
          </Field>
        </form>

        <FieldDescription>
          <Link
            to="/"
            className="text-sm underline underline-offset-4 hover:text-primary"
          >
            Back to sign in
          </Link>
        </FieldDescription>
      </FieldGroup>
    </div>
  );
}

export const Route = createFileRoute('/_auth/reset-password')({
  component: ResetPassword,
})

function ResetPassword() {
  return (
 
    <Suspense fallback={<div>Loading...</div>}>
      <ResetPasswordContent />
    </Suspense>
 
  );
}
