// src/routes/(auth)/signup/+page.svelte
<script lang="ts">
	import { username } from 'better-auth/plugins';
	import { superForm, type Infer, type SuperValidated } from 'sveltekit-superforms';
	import { zodClient } from 'sveltekit-superforms/adapters';
	import { signUpSchema } from '$lib/schemas';
	import { goto } from '$app/navigation';
	import { signUp, isUsernameAvailable } from '$lib/auth-client';
	import * as Form from '$components/ui/form';
	import { Input } from '$components/ui/input';
	import { Button } from '$components/ui/button';
	import * as Card from '$components/ui/card';
	import * as Alert from '$components/ui/alert';
	import { Loader2, X, CheckCircle, XCircle, CircleAlert, CheckCheckIcon } from '@lucide/svelte';

	let image = $state<File | null>(null);
	let imagePreview = $state<string | null>(null);

	let loading = $state(false);
	let serverError = $state<string | null>(null);
	let successMessage = $state<string | null>(null);

	// username availability state
	// TODO: probably check length and valid chars before calling API
	let usernameStatus = $state<'available' | 'unavailable' | 'checking' | null>(null);
	let usernameError = $state<string | null>(null);

	const { data } = $props<{
		form: SuperValidated<Infer<typeof signUpSchema>>;
		message?: string;
	}>();

	const form = superForm(data.form, {
		validators: zodClient(signUpSchema)
	});

	const { form: formData, enhance } = form;

	function handleImageChange(e: Event) {
		const target = e.target as HTMLInputElement;
		const file = target.files?.[0];
		if (file) {
			image = file;
			const reader = new FileReader();
			reader.onloadend = () => {
				imagePreview = reader.result as string;
			};
			reader.readAsDataURL(file);
		}
	}

	function removeImage() {
		image = null;
		imagePreview = null;
	}

	async function convertImageToBase64(file: File): Promise<string> {
		return new Promise((resolve, reject) => {
			const reader = new FileReader();
			reader.onloadend = () => resolve(reader.result as string);
			reader.onerror = reject;
			reader.readAsDataURL(file);
		});
	}

	//real-time username check with debounce
	let usernameTimeout: ReturnType<typeof setTimeout>;
	$effect(() => {
		if ($formData.username) {
			clearTimeout(usernameTimeout);
			usernameTimeout = setTimeout(async () => {
				usernameStatus = 'checking';
				usernameError = null;
				try {
					const res = await isUsernameAvailable({ username: $formData.username });
					if (res.data?.available) {
						usernameStatus = 'available';
					} else {
						usernameStatus = 'unavailable';
						usernameError = 'Username is already taken';
					}
				} catch (err) {
					usernameStatus = null;
					usernameError = 'Could not verify username';
				}
			}, 500);
		}
	});

	async function handleSignUp() {
		loading = true;
		serverError = null;
		successMessage = null;

		try {
			await signUp.email({
				email: $formData.email,
				password: $formData.password,
				name: $formData.name,

				username: $formData.username.toLowerCase(),
				displayUsername: $formData.username,
				image: image ? await convertImageToBase64(image) : '',
				callbackURL: '/threads',
				fetchOptions: {
					onResponse: () => {
						loading = false;
					},
					onRequest: () => {
						loading = true;
					},
					onError: (ctx) => {
						serverError = ctx.error.message;
					},
					onSuccess: async () => {
						successMessage = 'Account created successfully!';
						setTimeout(() => goto('/threads	'), 1500);
					}
				}
			});
		} catch (err) {
			serverError = (err as Error)?.message || 'Something went wrong';
		} finally {
			loading = false;
		}
	}
</script>

<Card.Root class="mx-auto w-full max-w-md">
	<Card.Header class="space-y-1">
		<Card.Title class="text-center text-2xl font-bold">Sign Up</Card.Title>
		<Card.Description class="text-center">
			Enter your details to create a new account
		</Card.Description>
	</Card.Header>

	<form on:submit|preventDefault={handleSignUp}>
		<Card.Content class="space-y-4">
			<!-- Alerts -->
			{#if serverError}
				<Alert.Root class="border-destructive" variant="destructive">
					<CircleAlert /><Alert.Title>Error</Alert.Title>
					<Alert.Description>{serverError}</Alert.Description>
				</Alert.Root>
			{/if}

			{#if successMessage}
				<Alert.Root
					class="border-green-600 text-green-600 dark:border-green-400 dark:text-green-400"
				>
					<CheckCheckIcon />
					<Alert.Title>Success</Alert.Title>
					<Alert.Description>{successMessage}</Alert.Description>
				</Alert.Root>
			{/if}
			<!-- Full Name -->
			<Form.Field {form} name="name">
				<Form.Control>
					{#snippet children({ props })}
						<Form.Label>Full Name</Form.Label>
						<Input placeholder="e.g. John Doe" {...props} bind:value={$formData.name} />
					{/snippet}
				</Form.Control>
				<Form.FieldErrors />
			</Form.Field>

			<!-- Username with availability indicator -->
			<Form.Field {form} name="username">
				<Form.Control>
					<Form.Label>Username</Form.Label>
					<div class="relative flex items-center">
						<Input placeholder="Choose a username" class="pr-10" bind:value={$formData.username} />
						{#if usernameStatus === 'checking'}
							<Loader2 size={18} class="absolute right-3 animate-spin text-muted-foreground" />
						{:else if usernameStatus === 'available'}
							<CheckCircle size={18} class="absolute right-3 text-green-500" />
						{:else if usernameStatus === 'unavailable'}
							<XCircle size={18} class="absolute right-3 text-red-500" />
						{/if}
					</div>
				</Form.Control>
				<Form.FieldErrors />
				{#if usernameError}
					<p class="mt-1 text-sm text-red-500">{usernameError}</p>
				{/if}
			</Form.Field>

			<!-- Email -->
			<Form.Field {form} name="email">
				<Form.Control>
					<Form.Label>Email</Form.Label>
					<Input type="email" placeholder="Enter your email" bind:value={$formData.email} />
				</Form.Control>
				<Form.FieldErrors />
			</Form.Field>

			<!-- Password -->
			<Form.Field {form} name="password">
				<Form.Control>
					<Form.Label>Password</Form.Label>
					<Input type="password" placeholder="Create a password" bind:value={$formData.password} />
				</Form.Control>
				<Form.FieldErrors />
			</Form.Field>

			<!-- Confirm Password -->
			<Form.Field {form} name="confirmPassword">
				<Form.Control>
					<Form.Label>Confirm Password</Form.Label>
					<Input
						type="password"
						placeholder="Confirm your password"
						bind:value={$formData.confirmPassword}
					/>
				</Form.Control>
				<Form.FieldErrors />
			</Form.Field>

			<!-- Profile Image -->
			<div class="grid gap-2">
				<Form.Field {form} name="image">
					<Form.Control>
						<Form.Label>Profile Image (optional)</Form.Label>

						<div class="flex items-end gap-4">
							{#if imagePreview}
								<div class="relative h-16 w-16 overflow-hidden rounded-sm">
									<img
										src={imagePreview}
										alt="Profile preview"
										class="h-full w-full object-cover"
									/>
								</div>
							{/if}
							<div class="flex w-full items-center gap-2">
								<Input
									id="image"
									type="file"
									accept="image/*"
									on:change={handleImageChange}
									class="w-full"
								/>
								{#if imagePreview}
									<X class="cursor-pointer" on:click={removeImage} />
								{/if}
							</div>
						</div>
					</Form.Control><Form.FieldErrors />
				</Form.Field>
			</div>

			<Button class="w-full" type="submit" disabled={loading || usernameStatus === 'unavailable'}>
				{#if loading}
					<Loader2 size={16} class="animate-spin" />
				{:else}
					Create an account
				{/if}
			</Button>
		</Card.Content>
	</form>

	<Card.Footer class="flex justify-center">
		<a href="/login" class="pt-5 text-sm text-muted-foreground hover:text-primary">
			Already have an account? Sign In
		</a>
	</Card.Footer>
</Card.Root>

// src/routes/_auth/sign-up.tsx


import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useForm } from "@tanstack/react-form";
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
  FieldError,
} from "~/components/ui/field";
import { Input } from "~/components/ui/input";
import { Button } from "~/components/ui/button";
import { signUpSchema } from "~/lib/schemas";
import { signUp } from "~/lib/auth-client";
import { UserPlus, X } from "lucide-react";
import { Spinner } from "~/components/ui/spinner";
import { Alert, AlertDescription, AlertTitle } from "~/components/ui/alert";
import { useState } from "react";
import { toast } from "sonner";
import { Label } from "~/components/ui/label";
import { seo } from '~/utils/seo'

export const Route = createFileRoute('/_auth/sign-up')({
  head: () => ({
    meta: [...seo({ title: 'Sign Up - Foreum', description: 'Create a Foreum account.' })],
  }),
  component: SignUp,
})

function SignUp() {
  const [serverError, setServerError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const navigate = useNavigate();

  const form = useForm({
    defaultValues: {
      name: "",
      username: "",
      email: "",
      password: "",
      confirmPassword: "",
      image: "",
    },
    validators: {
      onSubmit: signUpSchema,
    },
    onSubmit: async ({ value }) => {
      setIsLoading(true);
      setServerError(null);

      try {
        const result = await signUp.email({
          name: value.name,
          username: value.username,
          email: value.email,
          password: value.password,
          image: value.image || undefined,
        });

        if (result.error) {
          setServerError(result.error.message || "Registration failed");
          toast.error("Registration failed");
        } else {
          toast.success("Account created successfully!");
          navigate({ to: "/sign-in" });
        }
      } catch (error) {
        setServerError("An unexpected error occurred");
        toast.error("Registration failed");
      } finally {
        setIsLoading(false);
      }
    },
  });


  return (
   <div className="flex flex-col gap-6">
      <FieldGroup>
        <div className="flex flex-col gap-2">
          <h1 className="text-2xl font-bold">Create your account</h1>
          <p className="text-muted-foreground text-sm">
            Enter your details below to create your account
          </p>
        </div>

        {serverError && (
          <FieldError className="text-center">
            <Alert variant="destructive">
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>{serverError}</AlertDescription>
            </Alert>
          </FieldError>
        )}

        <form
          onSubmit={(e) => {
            e.preventDefault();
            e.stopPropagation();
            form.handleSubmit();
          }}
          className="flex flex-col gap-6"
        >
          <form.Field
            name="name"
            children={(field) => {
              const isInvalid =
                field.state.meta.isTouched && !field.state.meta.isValid;
              return (
                <Field data-invalid={isInvalid}>
                  <FieldLabel htmlFor={field.name}>Name</FieldLabel>
                  <Input
                    id={field.name}
                    name={field.name}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                    type="text"
                    placeholder="John Doe"
                    aria-invalid={isInvalid}
                    disabled={isLoading}
                  />
                  {isInvalid && (
                    <FieldError errors={field.state.meta.errors} />
                  )}
                </Field>
              );
            }}
          />

          <form.Field
            name="username"
            children={(field) => {
              const isInvalid =
                field.state.meta.isTouched && !field.state.meta.isValid;
              return (
                <Field data-invalid={isInvalid}>
                  <FieldLabel htmlFor={field.name}>Username</FieldLabel>
                  <Input
                    id={field.name}
                    name={field.name}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                    type="text"
                    placeholder="johndoe"
                    aria-invalid={isInvalid}
                    disabled={isLoading}
                  />
                  {isInvalid && (
                    <FieldError errors={field.state.meta.errors} />
                  )}
                </Field>
              );
            }}
          />

          <form.Field
            name="email"
            children={(field) => {
              const isInvalid =
                field.state.meta.isTouched && !field.state.meta.isValid;
              return (
                <Field data-invalid={isInvalid}>
                  <FieldLabel htmlFor={field.name}>Email</FieldLabel>
                  <Input
                    id={field.name}
                    name={field.name}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                    type="email"
                    placeholder="m@example.com"
                    aria-invalid={isInvalid}
                    disabled={isLoading}
                  />
                  {isInvalid && (
                    <FieldError errors={field.state.meta.errors} />
                  )}
                </Field>
              );
            }}
          />

          <form.Field
            name="password"
            children={(field) => {
              const isInvalid =
                field.state.meta.isTouched && !field.state.meta.isValid;
              return (
                <Field data-invalid={isInvalid}>
                  <FieldLabel htmlFor={field.name}>Password</FieldLabel>
                  <Input
                    id={field.name}
                    name={field.name}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                    type="password"
                    aria-invalid={isInvalid}
                    disabled={isLoading}
                  />
                  {isInvalid && (
                    <FieldError errors={field.state.meta.errors} />
                  )}
                </Field>
              );
            }}
          />

          <form.Field
            name="confirmPassword"
            children={(field) => {
              const isInvalid =
                field.state.meta.isTouched && !field.state.meta.isValid;
              return (
                <Field data-invalid={isInvalid}>
                  <FieldLabel htmlFor={field.name}>Confirm Password</FieldLabel>
                  <Input
                    id={field.name}
                    name={field.name}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(e) => field.handleChange(e.target.value)}
                    type="password"
                    aria-invalid={isInvalid}
                    disabled={isLoading}
                  />
                  {isInvalid && (
                    <FieldError errors={field.state.meta.errors} />
                  )}
                </Field>
              );
            }}
          />
          <form.Field
            name="image"
            children={(field) => {
              const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
                const file = e.target.files?.[0];
                if (file) {
                  const reader = new FileReader();
                  reader.onloadend = () => {
                    field.handleChange(reader.result as string);
                  };
                  reader.readAsDataURL(file);
                }
              };

              return (
                <Field>
                  <FieldLabel htmlFor={field.name}>Profile Image (optional)</FieldLabel>
                  <div className="flex items-end gap-4">
                    {field.state.value && (
                      <div className="relative size-16 rounded-sm overflow-hidden border">
                        <img
                          src={field.state.value}
                          alt="Profile preview"
                          className="h-full w-full object-cover"
                        />
                      </div>
                    )}
                    <div className="flex items-center gap-2 w-full">
                      <Input
                        id={field.name}
                        type="file"
                        accept="image/*"
                        onChange={handleImageChange}
                        className="w-full"
                      />
                      {field.state.value && (
                        <X
                          className="cursor-pointer"
                          onClick={() => {
                            field.handleChange("");
                          }}
                        />
                      )}
                    </div>
                  </div>
                  <FieldError errors={field.state.meta.errors} />
                </Field>
              );
            }}
          />
          <Field>
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading && <Spinner data-icon="inline-start" />}
              <UserPlus data-icon="inline-start" />
              Create Account
            </Button>
          </Field>
        </form>

        <FieldDescription>
          Already have an account?{" "}
          <Link to="/sign-in" className="underline underline-offset-4">
            Sign in
          </Link>
        </FieldDescription>
      </FieldGroup>
    </div>
 
  );
}
