// src/routes/_landing/cookies.tsx
import { createFileRoute } from "@tanstack/react-router"

export const Route = createFileRoute('/_landing/cookies')({
  component: CookiesPage,
})

 function CookiesPage(){
    return (
				<div className="mx-auto max-w-4xl px-4 py-20 sm:px-6 lg:px-8">
				<h1 className="font-heading mb-4 text-4xl font-bold text-foreground">Cookie Policy</h1>
				<p className="mb-8 text-muted-foreground">Last updated: January 1, 2024</p>

				<div className="prose prose-lg max-w-none">
					<div className="space-y-8 leading-relaxed text-muted-foreground">
			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">
					1. What Are Cookies
				</h2>
				<p>
					Cookies are small text files that are placed on your device when you visit our website.
					They help us provide you with a better experience by remembering your preferences and
					understanding how you use our Service.
				</p>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">
					2. How We Use Cookies
				</h2>
				<p className="mb-4">We use cookies for several purposes:</p>
				<ul className="list-disc space-y-2 pl-6">
					<li><strong>Essential Cookies:</strong> Required for the Service to function properly</li>
					<li><strong>Functional Cookies:</strong> Remember your preferences and settings</li>
					<li><strong>Analytics Cookies:</strong> Help us understand how you use the Service</li>
					<li><strong>Marketing Cookies:</strong> Used to deliver relevant advertisements</li>
				</ul>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">
					3. Types of Cookies We Use
				</h2>

				<h3 className="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">
					Essential Cookies
				</h3>
				<p className="mb-4">
					These cookies are necessary for the Service to function and cannot be disabled:
				</p>
				<ul className="list-disc space-y-2 pl-6">
					<li>Authentication cookies (keep you logged in)</li>
					<li>Security cookies (protect against fraud)</li>
					<li>Session cookies (maintain your session state)</li>
				</ul>

				<h3 className="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">
					Functional Cookies
				</h3>
				<p className="mb-4">These cookies enhance functionality and personalization:</p>
				<ul className="list-disc space-y-2 pl-6">
					<li>Language preferences</li>
					<li>Theme preferences (light/dark mode)</li>
					<li>Layout preferences</li>
					<li>Notification settings</li>
				</ul>

				<h3 className="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">
					Analytics Cookies
				</h3>
				<p className="mb-4">These cookies help us understand how visitors use our Service:</p>
				<ul className="list-disc space-y-2 pl-6">
					<li>Google Analytics (page views, session duration)</li>
					<li>Usage patterns and feature adoption</li>
					<li>Error tracking and performance monitoring</li>
				</ul>

				<h3 className="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">
					Marketing Cookies
				</h3>
				<p className="mb-4">These cookies are used to deliver relevant advertisements:</p>
				<ul className="list-disc space-y-2 pl-6">
					<li>Track advertising campaign effectiveness</li>
					<li>Deliver personalized advertisements</li>
					<li>Retargeting cookies</li>
				</ul>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">
					4. Third-Party Cookies
				</h2>
				<p className="mb-4">We use services from third parties that may set cookies on your device:</p>
				<ul className="list-disc space-y-2 pl-6">
					<li><strong>Google Analytics:</strong> Website analytics and reporting</li>
					<li><strong>Stripe:</strong> Payment processing</li>
					<li><strong>Intercom:</strong> Customer support and messaging</li>
					<li><strong>Social Media:</strong> Social sharing and login features</li>
				</ul>
				<p className="mt-4">
					These third parties have their own privacy policies governing their use of cookies.
				</p>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">
					5. Managing Cookies
				</h2>
				<p className="mb-4">You have several options for managing cookies:</p>

				<h3 className="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">
					Browser Settings
				</h3>
				<p className="mb-4">Most browsers allow you to:</p>
				<ul className="list-disc space-y-2 pl-6">
					<li>View and delete cookies</li>
					<li>Block third-party cookies</li>
					<li>Block all cookies</li>
					<li>Clear cookies when you close your browser</li>
				</ul>

				<h3 className="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">
					Cookie Preferences
				</h3>
				<p>
					You can manage your cookie preferences through our cookie consent banner or in your
					account settings. Note that disabling certain cookies may affect the functionality of the
					Service.
				</p>

				<h3 className="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">Opt-Out Links</h3>
				<ul className="list-disc space-y-2 pl-6">
					<li>
						<a
							href="https://tools.google.com/dlpage/gaoptout"
							className="text-primary hover:underline"
							target='_blank'
							rel="noopener">Google Analytics Opt-out</a>
					</li>
					<li>
						<a
							href="http://optout.aboutads.info/"
							className="text-primary hover:underline"
							target='_blank'
							rel="noopener">Digital Advertising Alliance Opt-out</a>
					</li>
					<li>
						<a
							href="http://optout.networkadvertising.org/"
							className="text-primary hover:underline"
							target='_blank'
							rel="noopener">Network Advertising Initiative Opt-out</a>
					</li>
				</ul>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">6. Cookie Duration</h2>
				<p className="mb-4">Cookies may be either:</p>
				<ul className="list-disc space-y-2 pl-6">
					<li>
						<strong>Session Cookies:</strong> Temporary cookies that expire when you close your browser
					</li>
					<li>
						<strong>Persistent Cookies:</strong> Remain on your device for a set period or until you
						delete them
					</li>
				</ul>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">
					7. Updates to This Policy
				</h2>
				<p>
					We may update this Cookie Policy from time to time to reflect changes in our practices or
					for legal reasons. We will notify you of any material changes by posting the new policy on
					this page.
				</p>
			</section>

			<section>
				<h2 className="font-heading mb-4 text-2xl font-semibold text-foreground">8. Contact Us</h2>
				<p>If you have questions about our use of cookies, please contact us at:</p>
				<ul className="mt-4 list-none space-y-2 pl-0">
					<li>Email: privacy@foreum.com</li>
					<li>Address: [Your Company Address]</li>
				</ul>
			</section>
		</div></div>
	</div>
    )
}

// src/routes/(landing)/cookies/+page.svelte
<svelte:head>
	<title>Cookie Policy - Foreum</title>
	<meta name="description" content="Cookie Policy for Foreum forum platform." />
</svelte:head>

<div class="mx-auto max-w-4xl px-4 py-20 sm:px-6 lg:px-8">
	<h1 class="font-heading mb-4 text-4xl font-bold text-foreground">Cookie Policy</h1>
	<p class="mb-8 text-muted-foreground">Last updated: January 1, 2024</p>

	<div class="prose prose-lg max-w-none">
		<div class="space-y-8 leading-relaxed text-muted-foreground">
			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">
					1. What Are Cookies
				</h2>
				<p>
					Cookies are small text files that are placed on your device when you visit our website.
					They help us provide you with a better experience by remembering your preferences and
					understanding how you use our Service.
				</p>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">
					2. How We Use Cookies
				</h2>
				<p class="mb-4">We use cookies for several purposes:</p>
				<ul class="list-disc space-y-2 pl-6">
					<li><strong>Essential Cookies:</strong> Required for the Service to function properly</li>
					<li><strong>Functional Cookies:</strong> Remember your preferences and settings</li>
					<li><strong>Analytics Cookies:</strong> Help us understand how you use the Service</li>
					<li><strong>Marketing Cookies:</strong> Used to deliver relevant advertisements</li>
				</ul>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">
					3. Types of Cookies We Use
				</h2>

				<h3 class="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">
					Essential Cookies
				</h3>
				<p class="mb-4">
					These cookies are necessary for the Service to function and cannot be disabled:
				</p>
				<ul class="list-disc space-y-2 pl-6">
					<li>Authentication cookies (keep you logged in)</li>
					<li>Security cookies (protect against fraud)</li>
					<li>Session cookies (maintain your session state)</li>
				</ul>

				<h3 class="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">
					Functional Cookies
				</h3>
				<p class="mb-4">These cookies enhance functionality and personalization:</p>
				<ul class="list-disc space-y-2 pl-6">
					<li>Language preferences</li>
					<li>Theme preferences (light/dark mode)</li>
					<li>Layout preferences</li>
					<li>Notification settings</li>
				</ul>

				<h3 class="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">
					Analytics Cookies
				</h3>
				<p class="mb-4">These cookies help us understand how visitors use our Service:</p>
				<ul class="list-disc space-y-2 pl-6">
					<li>Google Analytics (page views, session duration)</li>
					<li>Usage patterns and feature adoption</li>
					<li>Error tracking and performance monitoring</li>
				</ul>

				<h3 class="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">
					Marketing Cookies
				</h3>
				<p class="mb-4">These cookies are used to deliver relevant advertisements:</p>
				<ul class="list-disc space-y-2 pl-6">
					<li>Track advertising campaign effectiveness</li>
					<li>Deliver personalized advertisements</li>
					<li>Retargeting cookies</li>
				</ul>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">
					4. Third-Party Cookies
				</h2>
				<p class="mb-4">We use services from third parties that may set cookies on your device:</p>
				<ul class="list-disc space-y-2 pl-6">
					<li><strong>Google Analytics:</strong> Website analytics and reporting</li>
					<li><strong>Stripe:</strong> Payment processing</li>
					<li><strong>Intercom:</strong> Customer support and messaging</li>
					<li><strong>Social Media:</strong> Social sharing and login features</li>
				</ul>
				<p class="mt-4">
					These third parties have their own privacy policies governing their use of cookies.
				</p>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">
					5. Managing Cookies
				</h2>
				<p class="mb-4">You have several options for managing cookies:</p>

				<h3 class="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">
					Browser Settings
				</h3>
				<p class="mb-4">Most browsers allow you to:</p>
				<ul class="list-disc space-y-2 pl-6">
					<li>View and delete cookies</li>
					<li>Block third-party cookies</li>
					<li>Block all cookies</li>
					<li>Clear cookies when you close your browser</li>
				</ul>

				<h3 class="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">
					Cookie Preferences
				</h3>
				<p>
					You can manage your cookie preferences through our cookie consent banner or in your
					account settings. Note that disabling certain cookies may affect the functionality of the
					Service.
				</p>

				<h3 class="font-heading mt-6 mb-3 text-xl font-semibold text-foreground">Opt-Out Links</h3>
				<ul class="list-disc space-y-2 pl-6">
					<li>
						<a
							href="https://tools.google.com/dlpage/gaoptout"
							class="text-primary hover:underline"
							target="_blank"
							rel="noopener">Google Analytics Opt-out</a
						>
					</li>
					<li>
						<a
							href="http://optout.aboutads.info/"
							class="text-primary hover:underline"
							target="_blank"
							rel="noopener">Digital Advertising Alliance Opt-out</a
						>
					</li>
					<li>
						<a
							href="http://optout.networkadvertising.org/"
							class="text-primary hover:underline"
							target="_blank"
							rel="noopener">Network Advertising Initiative Opt-out</a
						>
					</li>
				</ul>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">6. Cookie Duration</h2>
				<p class="mb-4">Cookies may be either:</p>
				<ul class="list-disc space-y-2 pl-6">
					<li>
						<strong>Session Cookies:</strong> Temporary cookies that expire when you close your browser
					</li>
					<li>
						<strong>Persistent Cookies:</strong> Remain on your device for a set period or until you
						delete them
					</li>
				</ul>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">
					7. Updates to This Policy
				</h2>
				<p>
					We may update this Cookie Policy from time to time to reflect changes in our practices or
					for legal reasons. We will notify you of any material changes by posting the new policy on
					this page.
				</p>
			</section>

			<section>
				<h2 class="font-heading mb-4 text-2xl font-semibold text-foreground">8. Contact Us</h2>
				<p>If you have questions about our use of cookies, please contact us at:</p>
				<ul class="mt-4 list-none space-y-2 pl-0">
					<li>Email: privacy@foreum.com</li>
					<li>Address: [Your Company Address]</li>
				</ul>
			</section>
		</div>
	</div>
</div>
